chore(ts): fix errors related to this keyword
app.ts:22:24 - error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.
app.ts:20:42 An outer value of 'this' is shadowed by this container.

Correction for cd71fb109d990df1a5fa32a8e3a659bd9ee49226 commit.

Part of #35